### PR TITLE
Use catch(Throwable) {} in place of deprecated catch {}

### PR DESCRIPTION
**Pull request by nordlow**
I'd appreciate a tag accompanied with a dub reg sync as usual.

### CODE REVIEW

**Comment by ikod** [comment]
Hello @nordlow !

> I'd appreciate a tag accompanied with a dub reg sync as usual.
Thanks,
Done

**Comment by nordlow** [comment]
> Done

I don't see any bump at https://code.dlang.org/packages/ikod-containers.

**Comment by ikod** [comment]
> > Done
> 
> I don't see any bump at https://code.dlang.org/packages/ikod-containers.

that's strange as I bumped release on github 4 hours ago
image

**Comment by nordlow** [comment]
> that's strange as I bumped release on github 4 hours ago

I don't think the dub reg is bumped updated automatically from the latest github tag. You have to log in and do the bump manually last time I checked.

**Comment by ikod** [comment]
Looks like this changed at some moment.

Btw, how do you use my containers?

**Comment by nordlow** [comment]
> Looks like this changed at some moment. Btw, how do you use my containers?

Works now. Thanks. It's a dependency for https://github.com/symmetryinvestments/concurrency I'm using.

**Comment by ikod** [comment]
> > Looks like this changed at some moment. Btw, how do you use my containers?
> 
> Works now. Thanks. It's a dependency for https://github.com/symmetryinvestments/concurrency I'm using.

Nice, thanks!

**Pull request merged**
